version: '3.8'

services:
    backend:
        build: backend/
        volumes:
            - ./:/usr/src/app
        ports: 
            - 8008:8008
        networks:
            - deploy_network
        container_name: backend

    frontend:
        build: frontend/
        volumes:
            - ./:/usr/src/app
        depends_on:
            - backend
        ports: 
            - 80:8501
        networks:
            - deploy_network
        container_name: frontend

networks:
    deploy_network:
        driver: bridge