version: '3.8'

services:
    database:
        image: 'postgres'
        restart: always
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_PASSWORD=root
        volumes:
            - postgres_data:/var/lib/postgresql/data/
    backend:
        build: backend/
        volumes:
            - ./:/usr/src/app
        ports: 
            - 8008:8008
        networks:
            - deploy_network
        container_name: backend
        links:
            - 'database'

    frontend:
        build: frontend/
        volumes:
            - ./:/usr/src/app
        depends_on:
            - backend
        ports: 
            - 80:8501
        networks:
            - deploy_network
        container_name: frontend

networks:
    deploy_network:
        driver: bridge
volumes:
    postgres_data: